import "../styles/index.scss";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import BottomBar from "../components/ui/BottomBar";
import RightSidebar from "../components/ui/RightSidebar";
import LeftSidebar from "../components/ui/LeftSidebar";
import Navbar from "../components/ui/Navbar";
import Providers from "../providers/Providers";
import React from "react";
import ClientLayout from "../components/ui/ClientLayout";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={geist.className + " min-h-screen w-full bg-[var(--background)] text-[var(--foreground)]"}>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
